### ISSUE TITLE
Alphabetical Ordering

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [rahuldecoded/nutrient-bot#101]
The facts.txt file is not correctly alphabetically ordered. Will fix.

**Comment by rahuldecoded** [comment]
@BrunoGomesCoelho  would you like to contribute in this project?

**Comment by BrunoGomesCoelho** [comment]
Hey @rahuldecoded , I'm looking at a couple of python projects to help out, this is indeed one of them :) The only thing is the server issue seems a bit advanced for me, but I'm free to help out with other things
